//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.14 at 11:48:09 PM CEST 
//


package com.ddv.graph.xml.graph;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for appTypeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="appTypeType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="webApp"/&gt;
 *     &lt;enumeration value="database"/&gt;
 *     &lt;enumeration value="legacyApp"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "appTypeType")
@XmlEnum
public enum AppTypeType {

    @XmlEnumValue("webApp")
    WEB_APP("webApp"),
    @XmlEnumValue("database")
    DATABASE("database"),
    @XmlEnumValue("legacyApp")
    LEGACY_APP("legacyApp");
    private final String value;

    AppTypeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static AppTypeType fromValue(String v) {
        for (AppTypeType c: AppTypeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
