//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.14 at 11:48:01 PM CEST 
//


package com.ddv.graph.xml.service;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ddv.graph.xml.service package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Services_QNAME = new QName("http://ddv.com/service/", "services");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ddv.graph.xml.service
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ServicesType }
     * 
     */
    public ServicesType createServicesType() {
        return new ServicesType();
    }

    /**
     * Create an instance of {@link ServiceType }
     * 
     */
    public ServiceType createServiceType() {
        return new ServiceType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ServicesType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ddv.com/service/", name = "services")
    public JAXBElement<ServicesType> createServices(ServicesType value) {
        return new JAXBElement<ServicesType>(_Services_QNAME, ServicesType.class, null, value);
    }

}
